name: Build All Latest Assets

on:
  workflow_dispatch:

jobs:
  build-alpine:
    uses: ./.github/workflows/build-alpine.yml
  build-linux:
    uses: ./.github/workflows/build-linux.yml
  build-linuxstatic:
   uses: ./.github/workflows/build-linuxstatic.yml
  build-macos:
   uses: ./.github/workflows/build-macos.yml
  build-windows:
   uses: ./.github/workflows/build-windows.yml

  collect-artifacts:
    runs-on: ubuntu-latest
    needs: [build-alpine, build-linux, build-linuxstatic, build-macos, build-windows]
    steps:
      - run: echo Finished with builds
      - name: Download workflow artifacts
        uses: dawidd6/action-download-artifact@v2.24.3
        with:
          workflow: build-alpine.yml
          path: artifacts
      - name: Download workflow artifacts
        uses: dawidd6/action-download-artifact@v2.24.3
        with:
          workflow: build-linux.yml
          path: artifacts
      - name: Download workflow artifacts
        uses: dawidd6/action-download-artifact@v2.24.3
        with:
          workflow: build-linuxstatic.yml
          path: artifacts
      - name: Download workflow artifacts
        uses: dawidd6/action-download-artifact@v2.24.3
        with:
          workflow: build-macos.yml
          path: artifacts
      - name: Download workflow artifacts
        uses: dawidd6/action-download-artifact@v2.24.3
        with:
          workflow: build-windows.yml
          path: artifacts
      - run: ls -laR artifacts
